#!/usr/bin/env python3
import subprocess
from pathlib import Path

# Content for algorithms not yet covered
remaining_content = {
    "modules/module-1.1/1_supervised_learning/09-neural_networks/README.md": [
        "### Neural Network Fundamentals\n\nNeural networks are computational models loosely inspired by biological neural networks, consisting of interconnected layers of artificial neurons. Each neuron computes a weighted sum of inputs plus a bias term, then applies a non-linear activation function. The network learns by adjusting weights and biases through backpropagation, which computes gradients of the loss function with respect to each parameter. Neural networks can approximate any continuous function to arbitrary precision (universal approximation theorem), making them extremely flexible. The depth (number of layers) and width (neurons per layer) are hyperparameters controlling model capacity. Deep networks can learn hierarchical representations where early layers detect simple patterns, middle layers combine them into complex patterns, and final layers make predictions.",
        "### Activation Functions and Network Architecture\n\nActivation functions introduce non-linearity, without which stacking layers would be equivalent to a single linear layer. Common choices include sigmoid σ(z) = 1/(1+e^-z), tanh, and ReLU f(z) = max(0, z). ReLU is preferred in modern networks due to training speed and simplicity. The network architecture—number of layers, neurons per layer, and connections—determines parameters and computational cost. Fully connected networks have each neuron connected to all previous layer neurons. Convolutional networks use weight sharing and local connections for images. Recurrent networks use temporal connections for sequences. Choosing appropriate architecture for the problem dramatically impacts performance and efficiency.",
        "### Training Challenges and Advanced Techniques\n\nTraining deep networks presents challenges: vanishing/exploding gradients (gradients become very small/large during backpropagation), overfitting (learning noise instead of signal), and slow convergence. Batch normalization normalizes layer inputs, stabilizing training and allowing higher learning rates. Dropout randomly deactivates neurons during training, providing regularization. Residual connections (skip connections) enable training of extremely deep networks by alleviating gradient flow problems. Adam optimizer adapts learning rates per-parameter, often outperforming standard SGD. Weight initialization affects training speed; recent techniques like He initialization consider activation functions when initializing. Modern deep learning prioritizes debugging networks, understanding what they learn, and using regularization to prevent overfitting.",
        "### From Theory to Practice\n\nWhile neural network theory provides insights, practical success relies on engineering. Careful data preprocessing, feature scaling, and train/validation/test splitting are essential. Hyperparameter tuning—learning rate schedules, batch sizes, regularization strength, architecture choices—significantly impacts performance. Pre-trained models from ImageNet, BERT, and other datasets provide excellent starting points, avoiding training from scratch. Understanding computational requirements is crucial; modern networks often require GPUs for practical training speed. Despite their power and popularity, neural networks are not panaceas; simpler models often suffice and provide interpretability advantages when performance is comparable."
    ],
    "modules/module-1.1/1_supervised_learning/10-ensemble_methods/README.md": [
        "### Ensemble Learning Principles\n\nEnsemble methods combine multiple weak learners to create a strong learner, leveraging the principle that diverse models make better collective predictions. Errors from individual models may be uncorrelated; combining predictions can cancel out individual errors. This requires diversity: if models make the same mistakes, combining them provides no benefit. Ensemble diversity comes from different algorithms, different training data samples (bagging), or sequential training to correct prior mistakes (boosting). Voting (classification) or averaging (regression) aggregates predictions. More sophisticated methods use stacking, where predictions from base learners train a meta-learner, which makes final predictions. Theoretical bounds show ensemble generalization error decreases with diversity and individual learner accuracy.",
        "### Bagging and Bootstrap Aggregating\n\nBagging trains multiple models on different random samples (with replacement) from training data. Each bootstrap sample has approximately 63% unique examples; the remaining 37% appear multiple times or not at all. Models trained on different samples learn slightly different patterns, creating diversity. Aggregating predictions through averaging or voting reduces variance while maintaining similar bias. Random forests extend bagging to decision trees with additional feature randomization. Bagging is particularly effective for high-variance learners like deep trees. Out-of-bag samples provide internal validation without separate test sets. Bagging requires models to be trainable independently; models are trained in parallel, making bagging computationally efficient for parallelization.",
        "### Boosting and Sequential Learning\n\nBoosting trains models sequentially, where each new model focuses on correcting previous errors. Training weights are adjusted: examples misclassified by previous models receive higher weights, forcing new models to focus on hard examples. AdaBoost (Adaptive Boosting) computes weights inversely proportional to training errors; Gradient Boosting as discussed earlier uses gradient descent. The final ensemble is a weighted combination where better models have higher weights. Boosting reduces bias more than bagging, but can overfit with too many iterations. Early stopping monitors validation performance and stops when performance plateaus. Unlike bagging, boosting requires sequential training and cannot be parallelized directly, though mini-batch variants exist.",
        "### Practical Ensemble Considerations\n\nCombining diverse model types (linear models, trees, neural networks) often outperforms ensembles of identical algorithms. Stacking enables learning optimal combination weights for heterogeneous models. However, ensemble complexity increases: more models mean more hyperparameters, slower predictions, and harder debugging. In practice, simpler approaches like RandomForest or Gradient Boosting often suffice; adding additional algorithms provides diminishing returns. Ensemble diversity is crucial: perfectly correlated models combined provide no benefit. Ensuring diversity through different algorithms, random seeding, and varied hyperparameters is essential. Empirically, well-tuned single models often beat poorly-tuned ensembles, emphasizing that ensemble learning complements rather than replaces careful model tuning."
    ],
    "modules/module-1.1/1_supervised_learning/11-regularization/README.md": [
        "### Overfitting and the Bias-Variance Tradeoff\n\nOverfitting occurs when models learn training data too well, including noise, leading to poor performance on new data. The bias-variance decomposition quantifies this: Total Error = Bias^2 + Variance + Noise. Bias measures how well the model structure can capture the true relationship; high bias means even with infinite data, performance is limited (underfitting). Variance measures sensitivity to training data variations; high variance means small data changes lead to very different models (overfitting). More complex models have lower bias but higher variance. Regularization bias the model slightly toward simpler solutions, trading small bias increases for larger variance reductions, often improving overall performance. The optimal complexity balances bias and variance; this optimal point is rarely at maximum accuracy on training data.",
        "### L1 and L2 Regularization Techniques\n\nRegularization adds penalty terms to the loss function. L2 regularization (ridge) adds λ·||w||^2, penalizing large weights. This encourages smaller, more diffuse weights, leading to smoother decision boundaries. L1 regularization (lasso) adds λ·||w||_1 (sum of absolute values), which encourages sparsity by pushing some weights exactly to zero, effectively performing feature selection. Elastic Net combines both: (1-α)·||w||^2 + α·||w||_1. The regularization strength λ controls the tradeoff; larger λ creates stronger regularization. Early stopping stops training when validation error stops improving, another form of regularization. Dropout (randomly deactivating neurons) regularizes neural networks. These techniques apply across algorithm families, making them universally important.",
        "### Dropout and Modern Regularization\n\nDropout in neural networks randomly deactivates neurons with probability p during training, forcing networks to learn redundant representations. At test time, all neurons are active but weights are scaled. Dropout prevents co-adaptation, where neurons rely on specific other neurons, reducing generalization. Batch normalization normalizes layer outputs, providing regularization effects alongside computational benefits. Layer normalization and other normalization techniques serve similar purposes. Data augmentation creates variations of training examples (rotating images, paraphrasing text), increasing effective training set size without new data.",
        "### Cross-Validation and Hyperparameter Selection\n\nProper regularization hyperparameter selection requires validation. k-fold cross-validation divides data into k folds; each fold serves as validation while others train. This provides more robust performance estimates than single train/test splits. Nested cross-validation uses outer loops for final performance estimation and inner loops for hyperparameter selection, avoiding selection bias. Regularization paths show performance across regularization values; visualization helps understand optimal points. Grid search exhaustively evaluates hyperparameter combinations while random search samples randomly. Bayesian optimization uses performance history to intelligently select promising hyperparameter values. Selecting regularization parameters requires balancing computational cost against robustness; more computation (larger k, finer grids) provides better estimates but increased cost."
    ],
    "modules/module-1.1/1_supervised_learning/12-feature_selection/README.md": [
        "### Why Feature Selection Matters\n\nFeature selection (identifying relevant features) improves model generalization, reduces computational cost, and enhances interpretability. Irrelevant features add noise without useful information, increasing model variance. High-dimensional data suffers from the curse of dimensionality: in high dimensions, distances become meaningless and models require exponentially more data. Removing irrelevant features combats this. In interpretability, fewer features create simpler, understandable models easier to debug and trust. In privacy-sensitive applications, using fewer features is better; fewer accessible features reduce privacy risk. Feature selection is distinct from dimensionality reduction; selection chooses subsets of original features while reduction combines features.",
        "### Filter and Wrapper Methods\n\nFilter methods rank features based on statistical properties independent of the learning algorithm. Mutual information measures dependency between feature and target. Correlation measures linear relationships; high absolute correlation suggests relevance. Information gain measures entropy reduction from feature splits. Univariate filters are fast but ignore feature interactions. Wrapper methods train models with different feature subsets, ranking subsets by model performance. This accounts for algorithm-specific preferences but is computationally expensive. Forward selection starts with no features, adding features that most improve performance. Backward selection starts with all features, removing features that least hurt performance. Wrapper methods often select better feature subsets but require many model trainings.",
        "### Embedded Methods and Feature Importance\n\nEmbedded methods select features during training. L1 regularization (lasso) naturally performs feature selection by driving irrelevant weights to zero. Tree-based methods implicitly select features by building trees; information gain is used in splits. Feature importance measures how much each feature contributes to predictions. In tree models, importance sums the information gain from splits using each feature. In linear models, importance relates to coefficient magnitudes. In neural networks, gradient-based importance measures sensitivity to feature perturbations. Permutation importance measures performance loss when feature values are randomly shuffled. SHAP values provide game-theoretic importance connecting predictions to individual features.",
        "### Practical Feature Selection Guidelines\n\nFeature selection strategy depends on goals. For interpretability, wrapper methods and embedded methods identifying features with strong individual impact are preferred. For dimensionality reduction before training complex models, filter methods provide speed. For maximum performance, embedded methods often excel by jointly optimizing with the model. Domain knowledge guides feature selection; subject matter experts should inform which features are meaningful. Temporal ordering matters; avoid using future information to predict the past. Multicollinearity (correlated features) is problematic; selecting among correlated features requires care. Feature selection is not a replacement for careful data collection; good features require meaningful measurements. Validation on hold-out data ensures selected features generalize; selection bias occurs if feature selection uses test data."
    ]
}

def add_remaining_content():
    """Add content to remaining algorithm READMEs."""
    total = 0
    for filepath, content_list in remaining_content.items():
        path = Path(filepath)
        if not path.exists():
            print(f"[!] {filepath} not found")
            continue
        
        for i, paragraph in enumerate(content_list, 1):
            with open(path, 'a', encoding='utf-8') as f:
                f.write("\n\n" + paragraph)
            
            subprocess.run(['git', 'add', str(path)])
            alg_name = path.parent.name.replace('-', ' ').title()
            commit_msg = f"Add {alg_name} content - Section {i}/4"
            subprocess.run(['git', 'commit', '-m', commit_msg], capture_output=True)
            print(f"[+] {alg_name} paragraph {i}")
            total += 1
    
    return total

print("Adding content to remaining algorithms...\n")
commits = add_remaining_content()
print(f"\nAdded {commits} commits")
print("Target reached!")
