#!/usr/bin/env python3
import os
import subprocess
from pathlib import Path

# Content for unsupervised learning
unsupervised_content = {
    "01-kmeans": [
        "### Clustering Objective and Algorithm Overview\n\nK-means is an unsupervised learning algorithm that partitions data into k clusters by minimizing the within-cluster sum of squared distances. The algorithm begins by initializing k cluster centers (centroids) randomly or using smarter initialization strategies like k-means++. Each iteration comprises two steps: first, each data point is assigned to the nearest centroid (assignment step), and second, centroids are updated to the mean of all points assigned to each cluster (update step). This process repeats until convergence, when centroid positions no longer change significantly or a maximum iteration limit is reached. The algorithm optimizes the objective function J = Σ Σ ||x - μ_k||², where x are data points, μ_k are centroids, and the minimization is over all clusters. Despite its simplicity, k-means is widely used due to computational efficiency and reasonable performance in many applications.",
        "### Initialization Strategies and Local Optima\n\nA critical issue with k-means is its sensitivity to initialization; different random starting centroid positions can lead to different final clusters, some of which may be suboptimal. Random initialization often leads to poor local optima, where clusters are not well-separated. The k-means++ initialization algorithm addresses this by selecting the first centroid randomly, then iteratively choosing subsequent centroids with probability proportional to their squared distance from the nearest existing centroid. This biases initialization toward distant points, producing more separated starting centroids and better final solutions. Multiple random restarts followed by selecting the best result (lowest final cost) is another practical approach. Understanding that k-means is sensitive to initialization is crucial for practitioners; running the algorithm multiple times with different initializations and selecting the best result significantly improves solution quality without increasing algorithmic complexity.",
        "### Selecting k and Evaluation Metrics\n\nChoosing the number of clusters k is a fundamental challenge in k-means; the problem provides no inherent ground truth regarding the appropriate number of clusters. The elbow method plots the within-cluster sum of squared distances (WCSS) against k and selects the k where the curve shows an elbow or significant change in slope. The silhouette score measures how similar each point is to its cluster compared to other clusters, ranging from -1 to 1 where higher is better. Gap statistics compare observed clustering quality to that of random data. Davies-Bouldin index measures the average similarity between each cluster and the most similar cluster, with lower values indicating better separation. These metrics provide heuristics but no definitive answer; domain knowledge frequently informs the choice of k. Cross-validation on downstream tasks (if clustering is a preprocessing step) or expert judgment often provides the best guidance.",
        "### Scalability, Variants, and Limitations\n\nK-means has linear time complexity O(nkd) per iteration for n points, k clusters, and d dimensions, making it scalable to large datasets. Mini-batch k-means processes data in batches, further improving scalability through reduced memory requirements and computations per iteration. K-means clusters are spherical and similar-sized; elongated clusters or clusters with different densities challenge the algorithm as it minimizes Euclidean distance without accounting for cluster shape or local density. Soft k-means (fuzzy c-means) assigns points probabilistically to clusters rather than hard assignments, providing a softer clustering that captures uncertainty. K-medoids selects actual data points as cluster centers instead of means, making it more robust to outliers. Despite limitations, k-means remains fundamental in unsupervised learning for its speed, simplicity, and often adequate performance; it frequently serves as a baseline or preprocessing step in more sophisticated clustering approaches."
    ],
    "02-hierarchical_clustering": [
        "### Agglomerative and Divisive Hierarchical Clustering\n\nHierarchical clustering builds a tree-like structure (dendrogram) of nested clusters, allowing clusters at multiple granularities. Agglomerative clustering (bottom-up) starts with each point as its own cluster and recursively merges the two closest clusters until all points belong to one cluster. Divisive clustering (top-down) starts with all points in one cluster and recursively splits until each point is its own cluster. The agglomerative approach is more commonly used and computationally practical. The choice of linkage criterion determines how distances between clusters are computed. Single linkage uses the minimum distance between points from different clusters, tending to create long, chain-like clusters. Complete linkage uses the maximum distance, creating more compact clusters. Average linkage computes the average distance between all point pairs from different clusters, balancing extreme cases. Ward's method minimizes the increase in within-cluster variance, often producing well-separated, balanced clusters.",
        "### Dendrogram Interpretation and Cluster Selection\n\nThe dendrogram visualization displays the hierarchical structure as a tree where leaves are individual points and internal nodes represent cluster merges. The height of each merge indicates the distance between merged clusters; larger heights represent larger distances and more disparate clusters. The dendrogram reveals cluster structure at different scales, showing which points are similar and how clusters naturally nest within each other. Selecting clusters from a dendrogram can be done by cutting the tree at a specific height; above the cut, cluster assignments are determined. This flexible approach allows adjustment of cluster granularity without re-running the algorithm. The choice of cutting height involves similar considerations as selecting k in k-means: elbow methods, domain knowledge, and downstream task performance provide guidance. Dendrograms also reveal interesting structure such as obvious cluster outliers or subclusters within larger clusters.",
        "### Computational Complexity and Practical Considerations\n\nAgglomerative hierarchical clustering has O(n² log n) time complexity and O(n²) space complexity, making it less scalable than k-means for large datasets. The distance matrix of size n×n must be stored and updated iteratively as clusters merge. For very large datasets, sub-sampling or approximate methods become necessary. However, hierarchical clustering provides unique advantages: the dendrogram offers rich structural information beyond simple cluster assignments, the method is deterministic (no random initialization), and no specification of cluster number is required a priori. Hierarchical clustering performs well when the true cluster structure has a natural hierarchical organization. It is particularly useful in exploratory data analysis, taxonomy construction, and customer segmentation where hierarchical organization provides insights.",
        "### Hybrid Approaches and Integration with Other Methods\n\nIn practice, hierarchical clustering is often combined with other methods. Cutting a dendrogram at different heights and applying k-means to the resulting clusters (hierarchical-k-means) combines the strengths of both approaches. Consensus clustering applies multiple clustering algorithms and aggregates results, often using hierarchical clustering within the ensemble. Time-series data frequently benefits from hierarchical clustering combined with dynamic time warping distances rather than Euclidean distances. Document clustering uses hierarchical clustering with cosine similarity on TF-IDF vectors. Hierarchical clustering can serve as a preprocessing step to estimate k for k-means. Despite higher computational cost, the structural insights and flexibility of hierarchical clustering make it valuable in applications where interpretability and hierarchical organization are important."
    ],
    "03-pca": [
        "### Dimensionality Reduction and Variance Maximization\n\nPrincipal Component Analysis (PCA) is an unsupervised linear dimensionality reduction technique that identifies new features (principal components) that capture maximum variance in the data. The first principal component is the direction of maximum variance; the second principal component is orthogonal to the first and captures the second-most variance; and so on. These directions are eigenvectors of the data covariance matrix, ordered by descending eigenvalues (which represent variance along each direction). By selecting the top k principal components, we project high-dimensional data into a lower-dimensional subspace while retaining as much variance as possible. This variance-maximizing property ensures that important structure in data is preserved while removing noise and redundancy. PCA is unsupervised in that it does not use class labels; it discovers structure purely from feature correlations.",
        "### Computational Implementation and Interpretation\n\nConcretely, PCA involves computing the covariance matrix C = 1/n · X^T·X where X is the centered data matrix. The eigendecomposition of C yields eigenvectors (principal directions) and eigenvalues (variance along each direction). The top k eigenvectors form a projection matrix W, and data is projected as Y = X·W. Standard implementations use Singular Value Decomposition (SVD) rather than eigendecomposition directly, which is numerically more stable and efficient. The explained variance ratio for the k-th component is the percentage of total variance captured by that component, computed as λ_k / Σλ_i. Cumulative explained variance shows the proportion of total variance captured by the top k components. A scree plot shows eigenvalues (or explained variance) for each component; an elbow in this plot suggests the number of components to retain. Typically, components explaining 80-95% of total variance are retained, though application-specific requirements may differ.",
        "### Feature Reconstruction and Loss Analysis\n\nWhen projecting to lower dimensions, information is lost unless all variance is retained. The reconstruction error ||X - X_reconstructed||² measures information loss; perfectly retaining all variance means zero reconstruction error, while retaining only a fraction means non-zero error. The reconstruction error equals the sum of eigenvalues (variances) associated with discarded components. Therefore, minimizing retained components minimizes reconstruction error, directly reflecting our variance-maximization principle. For visualization purposes (k=2 or k=3), we accept significant reconstruction error in exchange for interpretable visualizations. For preprocessing steps in supervised learning, we select k to balance reconstruction error and computational efficiency; higher dimensionality better preserves information but increases downstream computation. Cross-validation can assess how dimensionality selection affects supervised learning performance.",
        "### Limitations and Extensions\n\nPCA identifies linear relationships and may miss nonlinear structure in data. Kernel PCA extends PCA to nonlinear dimensionality reduction by implicitly working in a high-dimensional kernel space. For data with highly non-Gaussian distributions, Independent Component Analysis (ICA) finds statistically independent components rather than maximum variance directions. PCA assumes continuous variables and can be affected by outliers due to the covariance matrix. Robust PCA variants use robust covariance estimators to handle outliers. For categorical variables, Multiple Correspondence Analysis (MCA) extends PCA logic. PCA whitening (normalizing by standard deviations) ensures all components have unit variance, which can be beneficial for downstream algorithms. Incremental PCA processes data in batches, enabling PCA on datasets too large to fit in memory. Despite limitations, PCA remains fundamental in unsupervised learning for visualization, denoising, and dimensionality reduction as a preprocessing step."
    ],
    "04-dbscan": [
        "### Density-Based Clustering and Eps-Neighbors\n\nDensity-Based Spatial Clustering of Applications with Noise (DBSCAN) groups points that are densely packed together and identifies points in sparse regions as outliers. Unlike k-means or hierarchical clustering, DBSCAN does not require specifying the number of clusters; instead, it uses two parameters: eps (neighbor distance threshold) and min_pts (minimum points in eps-neighborhood). A point p is a core point if its eps-neighborhood contains at least min_pts points. Points within the eps-neighborhood of a core point are density-reachable from that core point. A cluster is formed by all density-connected points, where points are transitively connected through core points. Points not in any cluster are classified as noise or outliers. This density-based definition allows clusters of arbitrary shape and size, making DBSCAN more flexible than k-means or hierarchical clustering.",
        "### Parameter Selection and Computational Aspects\n\nSelecting eps and min_pts is crucial and often requires domain knowledge or data characteristics. The k-distance graph plots sorted distances to the k-th nearest neighbor for each point; a kink or elbow in this graph suggests an appropriate eps value corresponding to cluster density. min_pts is sometimes set to dimensionality + 1 or 2*dimensionality. Smaller eps values lead to more outliers and fragmented clusters; larger values merge distinct clusters. DBSCAN has O(n²) complexity in the worst case but O(n log n) with spatial indexing structures like KD-trees or R-trees. This makes DBSCAN practical for datasets where k-means' need for many iterations becomes expensive. DBSCAN is particularly suitable for spatial point clustering, geographic data, and applications where outlier detection is important. The noise classification is valuable when true outliers require special handling rather than forced assignment to clusters.",
        "### Handling Varying Density Clusters\n\nA limitation of DBSCAN is difficulty with clusters of varying densities; a single eps cannot simultaneously capture dense and sparse clusters. In sparse regions, setting eps large enough to include sufficient points for dense clusters creates over-merged dense clusters. HDBSCAN (Hierarchical DBSCAN) addresses this by creating a hierarchy of density levels and extracting a flat clustering from stable clusters in this hierarchy, handling varying-density clusters effectively. OPTICS (Ordering Points to Identify Clustering Structure) computes a density-based ordering and visualization similar to DBSCAN but without fixing eps, allowing density flexibility. These extensions maintain DBSCAN advantages while improving handling of complex density distributions.",
        "### Applications and Theoretical Justification\n\nDBSCAN's ability to find arbitrary-shaped clusters makes it valuable for applications like document clustering, image clustering, and spatial data mining. The noise classification without forcing all points into clusters is theoretically justified: in many real problems, not all points belong to well-defined clusters. DBSCAN's definition of clusters is based on connectivity and density rather than artificial metrics like Euclidean distance, aligning well with many intuitive clustering notions. The flexibility to skip specifying cluster numbers is advantageous in exploratory analysis where the number of clusters is unknown. However, DBSCAN struggles with high-dimensional data where the concept of density becomes problematic (curse of dimensionality). Overall, DBSCAN remains a fundamental clustering algorithm, particularly for density-based cluster discovery in spatial and moderate-dimensional data."
    ],
    "05-gaussian_mixture_models": [
        "### Probabilistic Clustering and Gaussian Mixture Models\n\nGaussian Mixture Models (GMM) treat clustering as a probabilistic problem where data is assumed to come from a mixture of k Gaussian distributions. Each cluster is represented by a Gaussian with parameters (mean, covariance) and a mixing weight (proportion of data from that Gaussian). Unlike k-means which assigns points hard cluster membership, GMM provides soft assignments—a probability that each point belongs to each cluster. The likelihood function for GMM is p(X|θ) = Π Σ π_k·N(x_i|μ_k, Σ_k), where π_k are mixing weights, μ_k are means, and Σ_k are covariances. Maximum likelihood estimation of parameters is performed via Expectation-Maximization (EM), which iterates between computing expected cluster membership (E-step) and updating parameters (M-step). GMM provides a principled probabilistic framework for clustering, including uncertainty quantification through cluster membership probabilities.",
        "### The Expectation-Maximization Algorithm\n\nThe Expectation-Maximization algorithm is a general framework for maximum likelihood estimation with latent variables. In GMM context, cluster assignments are latent (unknown). The E-step computes the responsibility (posterior probability) that each point belongs to each cluster: γ(z_{ik}) = π_k·N(x_i|μ_k, Σ_k) / Σ_j π_j·N(x_i|μ_j, Σ_j). The M-step updates parameters: π_k ← 1/n·Σ γ(z_{ik}), μ_k ← Σ γ(z_{ik})·x_i / Σ γ(z_{ik}), and Σ_k is updated similarly. EM alternates between E and M steps with guaranteed monotonic increase in likelihood, converging to a local maximum. EM provides soft probabilistic assignments during and after training, contrasting with k-means' hard assignments. This probabilistic treatment allows expressing clustering uncertainty and using probability-based selection criteria.",
        "### Model Selection and Covariance Constraints\n\nSelecting the number of components (equivalent to selecting k) uses information criteria. The Bayesian Information Criterion (BIC) is BIC = -2 log L + p log n, balancing likelihood fit with model complexity (p is parameter count). Akaike Information Criterion (AIC) similarly balances fit and complexity with different penalties. Lower BIC/AIC indicates better models, so these metrics can be computed for different k values and the best k selected. The problem of GMM over-parameterization (unrestricted covariance matrices have O(k·d²) parameters) can be addressed by constraining covariance structure. Full covariance matrices allow Σ_k = [arbitrary symmetric positive-definite matrix] (most flexible). Diagonal covariance assumes independence between features within clusters. Spherical covariance assumes equal variance in all directions Σ_k = σ²_k·I. These constraints reduce parameters and regularize against overfitting.",
        "### Advantages and Limitations\n\nGMM advantages include probabilistic interpretation, soft cluster assignments enabling uncertainty quantification, and principled model selection through likelihood. GMM is well-suited for model-based clustering where underlying data generation matches Gaussian mixture assumptions. The soft assignments are useful for applications requiring confidence or where hard assignments are inappropriate. EM convergence guarantees local optima though not global optima, and multiple random initializations often improve results. However, GMM is sensitive to initialization and may converge to poor local optima. Computational complexity is O(k·d²·n·iterations), higher than k-means for complex covariance structures. GMM assumes Gaussian cluster shapes; non-Gaussian clusters may be poorly modeled. For very high-dimensional data, covariance estimation becomes unstable. Despite limitations, GMM provides a principled probabilistic framework valuable in applications where soft cluster assignments and likelihood-based model selection are important."
    ],
    "06-manifold_learning": [
        "### Non-linear Dimensionality Reduction and Manifold Hypothesis\n\nManifold learning encompasses techniques that assume high-dimensional data lies near a lower-dimensional manifold—a continuous surface embedded in high-dimensional space. Unlike PCA which finds linear subspaces, manifold learning methods discover non-linear structure. The manifold hypothesis posits that high-dimensional data with high geometric complexity may have low intrinsic dimensionality when measured along the manifold. Manifold learning is motivated by phenomena like human perception: images of faces or handwritten digits, though high-dimensional (thousands of pixels), have low intrinsic dimensionality because only a few factors of variation (pose, lighting, digit style) control them. Discovering these factors and reducing to a low-dimensional representation that preserves manifold structure is the goal of manifold learning. This is valuable when data lies on complex non-linear structure that linear methods like PCA fail to capture.",
        "### t-SNE: Non-linear Dimensionality Reduction for Visualization\n\nt-Distributed Stochastic Neighbor Embedding (t-SNE) is a popular manifold learning technique designed for visualization. t-SNE converts high-dimensional point similarities to low-dimensional Euclidean distances while preserving local neighborhood structure. In high dimensions, similarities are computed as P(j|i) = exp(-||x_i - x_j||²/(2σ_i²)) / Σ_k≠i exp(-||x_i - x_k||²/(2σ_i²)), balancing local and global structure. In low dimensions, t-SNE uses the t-distribution for robustness: Q(j|i) = (1 + ||y_i - y_j||²)^(-1) / Σ_k≠i (1 + ||y_i - y_k||²)^(-1). Kullback-Leibler divergence between P and Q is minimized using gradient descent. t-SNE excels at discovering cluster structure and reproducing local neighborhoods but doesn't preserve global distances; close points in the original space remain close in t-SNE space, but distant points may or may not remain distant. Therefore, t-SNE is most suitable for visualization rather than building features for downstream learning.",
        "### Isomap and Locally Linear Embedding\n\nIsomap extends multidimensional scaling by using geodesic distances (distances along the manifold) rather than Euclidean distances. A k-nearest neighbor graph is constructed, with edge weights as Euclidean distances. Shortest paths in this graph approximate geodesic distances. Classical multidimensional scaling is applied to the geodesic distance matrix, producing a low-dimensional embedding that preserves manifold structure. Isomap discovers the underlying manifold structure better than PCA when the manifold has non-trivial topology. Locally Linear Embedding (LLE) assumes each point and its k-nearest neighbors lie on a locally linear patch of the manifold. LLE reconstructs each point as a linear combination of its neighbors: x_i ≈ Σ_j w_{ij}·x_j, minimizing reconstruction error. The same weights are applied in low dimensions to preserve local linear structure. LLE captures manifold structure through local neighborhoods and often produces interpretable embeddings.",
        "### Applications and Computational Considerations\n\nManifold learning is valuable for visualization (t-SNE), feature learning (Isomap, LLE), and data exploration in high-dimensional spaces. These methods have revealed interesting structure in digit images, face images, natural language documents, and many other domains. However, manifold learning methods lack theoretical guarantees and have hyperparameters (neighborhood size for LLE/Isomap, perplexity for t-SNE) requiring careful selection. Computational complexity ranges from O(n²) to O(n³), making these methods less scalable than PCA. t-SNE has no inverse mapping, so new points cannot be projected. Recent advances include parametric t-SNE and parametric UMAP enabling inverse mappings. UMAP (Uniform Manifold Approximation and Projection) provides faster alternatives to t-SNE with better theoretical foundations. Despite computational costs, manifold learning remains essential for exploratory data analysis and has contributed significantly to understanding structure in complex high-dimensional datasets."
    ]
}

# Content for reinforcement learning
rl_content = {
    "01-qlearning": [
        "### Markov Decision Processes and Q-Values\n\nQ-learning operates within the framework of Markov Decision Processes (MDPs), which model sequential decision-making under uncertainty. An MDP consists of states S, actions A, transition probabilities P(s'|s, a), rewards R(s, a, s'), and a discount factor γ ∈ [0, 1]. The goal is to find an optimal policy π* that maximizes expected cumulative discounted reward. The Q-function Q(s, a) represents the expected cumulative reward from taking action a in state s and following the optimal policy thereafter: Q(s, a) = E[R(s, a, s') + γ max_{a'} Q(s', a')]. Q-values satisfy the Bellman optimality equation, providing the foundation for Q-learning. The optimal policy is determined greedily from Q-values: π*(s) = argmax_a Q(s, a). Q-learning directly estimates Q-values from experience without requiring knowledge of transition probabilities or rewards, making it model-free and practical.",
        "### Off-Policy Learning and the Q-Learning Update Rule\n\nQ-learning is off-policy, meaning it learns the optimal policy while following a different behavior policy for exploration. This flexibility allows improving exploration while learning optimal behavior. The Q-learning update rule is: Q(s, a) ← Q(s, a) + α[R(s, a, s') + γ max_{a'} Q(s', a') - Q(s, a)], where α is the learning rate and the bracketed term is the temporal difference (TD) error. This update moves Q-values toward the Bellman target R + γ max Q(s', a'). The learning rate α ∈ (0, 1] balances between incorporating new information (high α) and stability (low α). Decreasing α over time creates robust convergence. The discount factor γ balances immediate and long-term rewards; γ near 1 prioritizes long-term rewards while γ near 0 prioritizes immediate rewards. Q-learning converges to the optimal Q* under the conditions of adequate exploration and decreasing learning rates.",
        "### Exploration-Exploitation Trade-off and Strategies\n\nDuring learning, agents must balance exploring unknown actions to discover reward opportunities versus exploiting known good actions. Pure exploitation quickly gets stuck in local optima; pure exploration wastes samples. ε-greedy strategies take random actions with probability ε and greedy actions otherwise. Decaying ε from high to low values provides initial exploration followed by exploitation convergence. Softmax/Boltzmann exploration selects actions with probability proportional to exp(Q(s, a)/τ), providing smooth probabilistic exploration. Temperature τ controls randomness; high τ approaches uniform random exploration while low τ approaches greedy selection. Upper Confidence Bound (UCB) balances exploration and exploitation by selecting actions with highest uncertainty-adjusted Q-values. Optimistic initialization of Q-values encourages initial exploration. The choice of exploration strategy significantly impacts learning efficiency; sophisticated strategies substantially reduce sample complexity compared to simple ε-greedy.",
        "### Convergence, Limitations, and Deep Q-Learning\n\nQ-learning theoretically converges to the optimal Q* under mild conditions, but convergence in practice depends on proper hyperparameter settings and sufficient exploration. Q-learning faces challenges with large state spaces: the tabular representation requires O(|S||A|) memory and computation. For continuous states, function approximation (neural networks) approximates Q-values: Q(s, a; θ) ≈ Q(s, a). However, neural network approximation can destabilize learning due to non-stationarity of targets (network parameters change during learning). Deep Q-Networks (DQN) address this through experience replay (storing and sampling past transitions) and target networks (slowly updating copies of the main network). These techniques substantially improve convergence and sample efficiency. DQN achieved superhuman performance on Atari games, demonstrating Q-learning's power when combined with modern neural networks. Despite successes, Q-learning and its extensions remain sensitive to hyperparameters and may suffer from overestimation bias or divergence without careful tuning."
    ],
    "02-policy_gradient": [
        "### Policy Parameterization and Gradient Estimation\n\nPolicy gradient methods directly optimize the policy function π(a|s; θ) parameterized by θ (often neural network weights) to maximize expected cumulative reward J(θ) = E_π[Σ γ^t r_t]. Rather than learning state-action values, we learn the policy directly. The policy gradient theorem establishes: ∇_θ J(θ) = E[∇_θ log π(a|s; θ) Q(s, a)], relating policy gradient to Q-values. This gradient indicates how to adjust policy parameters to increase probability of better actions (high Q(s, a)) and decrease probability of worse actions (low Q(s, a)). Policy parameterization using neural networks is flexible: discrete action spaces use softmax output for action probabilities, continuous spaces use Gaussian distributions with mean and variance networks. The log probability derivative ∇_θ log π(a|s; θ) is easily computed; for softmax outputs it reduces to feature vectors minus expected features under the policy.",
        "### Advantage Estimation and Variance Reduction\n\nA key challenge in policy gradient learning is high variance in gradient estimates. The basic REINFORCE algorithm uses full trajectory returns as returns: ∇_θ log π(a_t|s_t; θ) · G_t where G_t = Σ_{k=t}^T γ^{k-t} r_k. This unbiased but high-variance gradient estimate requires many samples per update. Advantage Actor-Critic methods use advantage functions A(s, a) = Q(s, a) - V(s) representing how much better an action is than average. The policy gradient becomes ∇_θ J(θ) = E[∇_θ log π(a|s; θ) · A(s, a)]. Advantage estimation reduces variance substantially while introducing small bias. Temporal difference (TD) advantages use: A(s, a) = r + γV(s') - V(s), requiring only one-step lookahead. Generalized Advantage Estimation (GAE) interpolates between TD and full-return advantages, balancing bias and variance through a parameter λ ∈ [0, 1]. Advantage estimation is crucial for practical policy gradient methods.",
        "### Trust Region and Natural Gradient Methods\n\nUnconstrained policy gradient updates can cause divergence through excessively large parameter changes. Trust region methods constrain updates within regions where the linear approximation of policy performance is valid. Trust Region Policy Optimization (TRPO) constrains updates to regions where KL divergence from the old policy stays below δ: constrain KL(π_old || π_new) ≤ δ. This prevents destructively large parameter changes. Proximal Policy Optimization (PPO) simplifies TRPO using a clipped objective: min[r_t(θ)·A_t, clip(r_t(θ), 1-ε, 1+ε)·A_t] where r_t = π(a|s; θ) / π(a|s; θ_old). Clipping prevents probability ratios from deviating too far from 1, limiting update magnitude. PPO combines computational simplicity with stability, becoming extremely popular. Natural gradient methods use the Fisher information matrix to better adapt step sizes across parameter dimensions, improving convergence. These advances make policy gradient methods stable and practical.",
        "### Policy Gradient Variants and Applications\n\nBatch policy gradient methods (policy gradient + advantage actor-critic) collect transitions for multiple steps, accumulating advantages and computing policy gradients. On-policy methods learn from currently-generated trajectories, discarding old data; off-policy variants like Importance Weighted Policy Gradients correct for distribution mismatch. Continuous control problems benefit from policy gradient methods that naturally handle continuous action spaces. Robotics, control, and game-playing leverage policy gradients. REINFORCE, Actor-Critic, A3C (Asynchronous Advantage Actor-Critic), PPO, and TRPO form a family of increasingly sophisticated policy gradient algorithms. Despite high variance in basic forms, modern policy gradient methods with variance reduction, trust regions, and natural gradients achieve excellent performance. Policy gradients complement value-based methods; combining both in actor-critic architectures provides significant benefits over either alone."
    ],
    "03-actor_critic": [
        "### Actor-Critic Architecture\n\nActor-Critic methods combine policy-based and value-based learning by maintaining two components: an actor that learns the policy π(a|s; θ) and a critic that learns the value function V(s; φ). The actor generates actions based on the learned policy; the critic provides feedback through temporal difference (TD) errors: δ_t = r_t + γV(s_{t+1}; φ) - V(s_t; φ). The TD error indicates whether the reward was better or worse than expected: positive error suggests the action was better than average and should be encouraged, negative error suggests it was worse. Policy gradients use advantage estimates from the critic: ∇_θ J(θ) ≈ ∇_θ log π(a|s; θ) · δ_t. The actor updates using policy gradient with advantage from the critic. The critic updates using TD learning: φ ← φ + β·δ_t·∇_φ V(s; φ). This combination provides lower-variance gradient estimates than pure policy gradients (critic reduces variance) while maintaining faster convergence than pure value-based methods (policy gradient provides better direction).",
        "### Advantage Actor-Critic and Asynchronous Methods\n\nAdvantage Actor-Critic (A2C) generalizes basic actor-critic with more sophisticated advantage estimation. Generalized Advantage Estimation (GAE) provides a principled way to estimate advantages: A_t = Σ_{l=0}^∞ (γλ)^l δ_{t+l}. The parameter λ ∈ [0, 1] interpolates between TD advantage (λ=0, high bias, low variance) and full-return advantage (λ=1, low bias, high variance). Intermediate values balance bias and variance. Asynchronous Advantage Actor-Critic (A3C) parallelizes learning by running multiple agents in parallel environments, each with their own actor and critic. Periodically, gradients accumulated by parallel agents are applied to global actor and critic networks. This parallelization reduces wall-clock training time substantially while improving sample efficiency through diverse exploration. A3C was highly influential in demonstrating that synchronized non-policy methods like supervised learning could be parallelized effectively. Distributed variants of A2C and improvements like IMPALA extend these ideas further.",
        "### Entropy Regularization and Exploration\n\nPolicy gradient methods can converge prematurely to deterministic policies with low entropy. Entropy regularization adds an entropy bonus to the objective: J(θ) = E[log π(a|s; θ)·A + β·H(π(·|s; θ))], where H is policy entropy and β controls the trade-off. Entropy regularization encourages maintaining exploratory randomness even as the policy improves. The entropy bonus is H = -Σ π(a|s; θ) log π(a|s; θ). Tuning β is important; too low a β provides insufficient exploration, too high encourages excessive randomness. Entropy-regularized actor-critic learning naturally balances exploration and exploitation. This approach avoids explicit exploration strategies like ε-greedy and maintains exploration benefits that improve robustness. Entropy regularization is used in many modern algorithms including PPO and A3C.",
        "### Stability, Convergence, and Practical Considerations\n\nActor-critic methods can suffer from instability due to non-stationary targets (critic changes while learning policy) and correlated experience (sequential states are highly correlated). Modern variations address these issues through experience replay, target networks, and synchronized updates across multiple parallel workers. The choice of network architectures for actor and critic significantly impacts performance; shared layers between actor and critic can improve learning efficiency while separate networks provide more flexibility. Careful hyperparameter tuning is essential: learning rates for actor and critic often differ, GAE parameter λ requires tuning, and entropy regularization strength β must be selected. Despite challenges, modern actor-critic methods (A3C, PPO, TRPO) have become some of the most practical and effective reinforcement learning algorithms, achieving strong performance on diverse continuous control and game-playing tasks. The combination of value and policy-based learning through actor-critic provides complementary strengths."
    ],
    "04-deep_q_networks": [
        "### Deep Q-Networks: Function Approximation with Neural Networks\n\nDeep Q-Networks (DQN) applies Q-learning with neural networks to approximate the Q-function: Q(s, a; θ) ≈ Q(s, a). A neural network with parameters θ maps states to action values; the output layer has |A| units (one per action). During training, a batch of states is forward-passed through the network; gradients are computed from the loss (Q(s, a; θ) - target)². However, directly using neural networks for Q-learning creates instability: targets constantly change as network parameters θ change, and sequential states are correlated, violating the IID assumption underlying optimization. These problems caused early Q-learning with neural networks to diverge. DQN introduced two key stabilization techniques: experience replay and target networks, enabling stable deep reinforcement learning.",
        "### Experience Replay and Target Networks\n\nExperience replay stores transitions (s, a, r, s') in a replay buffer, a large memory storing recent experiences. During training, minibatches are sampled randomly from this buffer rather than using sequential transitions. Random sampling breaks correlations between samples, satisfying IID assumptions and stabilizing learning. The target network is a separate copy of the Q-network that is updated infrequently (every C steps or after certain number of gradient steps). During training, the target is computed using the older target network weights: target = r + γ max_{a'} Q(s', a'; θ_target). The main network weights θ are updated to match this target. Periodically, target network weights are synchronized with main network weights: θ_target ← θ. This decoupling provides slowly-changing targets, stabilizing training substantially. The combination of experience replay and target networks was revolutionary, making deep Q-learning stable and practical.",
        "### Double DQN and Dueling Architectures\n\nDQN tends to overestimate Q-values because max_{a'} Q(s', a'; θ_target) uses the same network to select and evaluate actions. Double DQN addresses this by decoupling action selection and evaluation: target = r + γ Q(s', argmax_{a'} Q(s', a'; θ); θ_target). Actions minimizing overestimation are selected using the main network, then evaluated using the target network. This simple change substantially improves performance. Dueling DQN decomposes the Q-function into state value and advantage streams: Q(s, a; θ) = V(s; θ) + A(s, a; θ), where V(s) is the value of state s and A(s, a) is the advantage of action a. Separate streams learn value and advantages; combining them through addition recovers Q-values. Dueling architecture provides richer learning signals, leveraging advantages without explicit subtraction from Q-values. Combining dueling architecture with double DQN provides further performance improvements. Prioritized Experience Replay samples transitions with probability proportional to TD error magnitude, focusing learning on high-error transitions.",
        "### Extensions and Practical Implementations\n\nDueling Double DQN combines benefits of both improvements. Rainbow DQN integrates multiple improvements: double Q-learning, prioritized experience replay, dueling networks, multi-step returns, distributional RL, and noisy networks. Distributional RL learns the full distribution of returns rather than just expectations, providing richer value representations. Noisy networks use noise in parameters for exploration rather than ε-greedy, creating more consistent exploration strategies. Modern implementations address computational efficiency and stability through various engineering improvements. Rainbow DQN achieved near-superhuman performance on Atari 2600 games, demonstrating DQN's potential when combined with multiple improvements. Despite advances, DQN-family algorithms remain primarily suitable for discrete action spaces; continuous control requires different approaches like policy gradients or actor-critic methods. DQN demonstrated that combining deep learning with reinforcement learning through careful stabilization techniques enables learning complex behaviors directly from high-dimensional sensory data, founding the deep reinforcement learning field."
    ]
}

def add_content_with_commits(module_dir, section, subdir, content_list):
    """Add content to README.md with individual commits."""
    readme_path = Path(module_dir) / section / subdir / "README.md"
    
    if not readme_path.exists():
        print(f"[!] README not found: {readme_path}")
        return False
    
    # Add each paragraph with a commit
    for i, paragraph in enumerate(content_list, 1):
        # Add content to file
        with open(readme_path, 'a', encoding='utf-8') as f:
            f.write("\n\n" + paragraph)
        
        # Stage and commit
        base_dir = str(Path(module_dir).parent.parent.parent)
        subprocess.run(['git', 'add', str(readme_path)], cwd=base_dir)
        commit_msg = f"Add {subdir.replace('-', ' ').title()} content - Section {i}/4"
        subprocess.run(['git', 'commit', '-m', commit_msg], cwd=base_dir)
        print(f"[+] Committed: {section}/{subdir} - Paragraph {i}/4")
    
    return True

# Main execution
module_1_1 = Path("modules/module-1.1")
total_commits = 0

print("=== UNSUPERVISED LEARNING ===\n")
for algo, content in unsupervised_content.items():
    print(f"Processing {algo}...")
    if add_content_with_commits(module_1_1, "2_unsupervised_learning", algo, content):
        total_commits += 4
        print(f"  → Total commits: {total_commits}\n")

print("\n=== REINFORCEMENT LEARNING ===\n")
for algo, content in rl_content.items():
    print(f"Processing {algo}...")
    if add_content_with_commits(module_1_1, "3_reinforcement_learning", algo, content):
        total_commits += 4
        print(f"  → Total commits: {total_commits}\n")

print("\n[OK] Added {} commits for unsupervised and reinforcement learning".format(total_commits))
