#!/usr/bin/env python3
import os
import subprocess
from pathlib import Path

# Define module content for each section with 4 paragraphs
content_map = {
    "01-linear_regression": [
        "### Mathematical Foundations\n\nLinear regression is fundamentally based on the principle of minimizing the sum of squared errors between predicted and actual values. The cost function, also known as the Mean Squared Error (MSE), is defined as J(θ) = 1/(2m) * Σ(h(x) - y)², where h(x) represents the hypothesis function and m is the number of training examples. This quadratic cost function creates a convex optimization landscape, ensuring that any local minimum found is also the global minimum. Understanding this mathematical foundation is crucial for implementing optimization algorithms like gradient descent effectively.",
        "### Gradient Descent Optimization\n\nGradient descent is the iterative optimization algorithm used to find the parameters that minimize the cost function. The algorithm works by computing the partial derivatives of the cost function with respect to each parameter and moving in the direction of steepest descent. The learning rate (alpha) is a critical hyperparameter that controls the size of each step taken during optimization. A learning rate that is too small will result in slow convergence, while a learning rate that is too large may cause the algorithm to overshoot the optimal solution. Choosing an appropriate learning rate requires careful consideration and often involves experimentation with different values.",
        "### Feature Scaling and Normalization\n\nWhen features have vastly different scales, gradient descent can converge slowly and may struggle to find optimal parameters. Feature scaling techniques such as standardization (z-score normalization) and mean normalization help ensure that all features contribute equally to the optimization process. Standardization transforms features to have zero mean and unit variance, computed as (x - mean) / standard_deviation. Without proper feature scaling, features with larger numerical ranges can dominate the learningprocess, leading to a model that does not properly utilize all available information in the training data.",
        "### Regularization and Model Complexity\n\nOverfitting occurs when a linear regression model learns the noise in the training data rather than the underlying pattern, resulting in poor performance on new, unseen data. Regularization techniques add a penalty term to the cost function to discourage overly complex models. Ridge regression adds an L2 penalty proportional to the square of the coefficients, while Lasso regression adds an L1 penalty proportional to the absolute value of the coefficients. The regularization parameter (lambda) controls the strength of the penalty; higher values lead to smaller coefficients and simpler models, while lower values allow for more complex models. Cross-validation can be used to find the optimal regularization parameter that balances model complexity and generalization performance."
    ],
    "02-logistic_regression": [
        "### The Sigmoid Function and Probability\n\nUnlike linear regression which predicts continuous values, logistic regression is designed for binary classification problems. The core of logistic regression is the sigmoid function, defined as σ(z) = 1 / (1 + e^(-z)), which maps any input to a value between 0 and 1. This output is interpreted as the probability that an instance belongs to the positive class. The sigmoid function has a smooth S-shaped curve that ensures the probability estimates are always bounded between 0 and 1, making it ideal for modeling classification probabilities. The decision boundary is typically set at 0.5, where instances with probability above 0.5 are classified as positive and those below are classified as negative.",
        "### Cross-Entropy Loss and Cost Function\n\nWhile logistic regression models probabilities, the cost function used for optimization is different from linear regression. The cross-entropy loss (also called log loss) is defined as -[y*log(h(x)) + (1-y)*log(1-h(x))], where y is the true label and h(x) is the predicted probability. This cost function has several desirable properties: it penalizes confident but incorrect predictions heavily, rewards confident correct predictions, and creates a convex optimization landscape. The logarithmic scale ensures that as the predicted probability moves away from the true label, the penalty increases exponentially. This property makes the cross-entropy loss particularly effective for training classification models as it naturally encourages the model to produce well-calibrated probability estimates.",
        "### Multiclass Classification Extension\n\nWhile binary logistic regression handles two-class problems, many real-world applications require classifying instances into more than two classes. Multiclass logistic regression extends the binary case using the softmax function, which generalizes the sigmoid function to multiple classes. The softmax function computes probabilities for each class such that they sum to 1, allowing the model to rank all classes and select the one with the highest probability. The cost function for multiclass problems becomes categorical cross-entropy, computed as -Σ(y_i * log(p_i)) where y_i is the true label indicator and p_i is the predicted probability for class i. This framework enables logistic regression to handle complex multi-class problems while maintaining the interpretability of probability estimates.",
        "### Practical Implementation Considerations\n\nImplementing logistic regression requires careful attention to several practical aspects beyond the theoretical foundations. Feature engineering remains critical; categorical variables must be encoded, and continuous features should be scaled to improve convergence. Class imbalance, where one class is significantly more prevalent than others, can bias the model toward the majority class. Techniques like stratified sampling, class weights, and resampling can address this issue. Additionally, threshold selection for classification is not always 0.5; depending on the application, moving the decision threshold can optimize metrics like precision, recall, or F1-score. Finally, regularization strategies apply to logistic regression just as they do to linear regression, and practitioners should use techniques like L1 or L2 regularization to prevent overfitting and improve model generalization."
    ],
    "03-decision_trees": [
        "### Tree Construction and Splitting Criteria\n\nDecision trees recursively partition the feature space into regions where each region is assigned a class label or prediction. The tree construction process begins with all training data at the root node and recursively selects the feature and split value that best separates the data into homogeneous subsets. Common splitting criteria for classification include Gini impurity and Information Gain based on entropy. Gini impurity measures the probability of misclassifying a randomly chosen element and is defined as 1 - Σ(p_i)², where p_i is the proportion of class i. Information Gain uses entropy, H = -Σ(p_i * log(p_i)), to measure the disorder in a dataset and selects splits that maximize the reduction in entropy. For regression tasks, variance reduction is used as the splitting criterion, selecting splits that minimize the variance within resulting subsets.",
        "### Pruning and Preventing Overfitting\n\nDecision trees have a natural tendency to overfit training data, growing until each leaf node contains only instances of a single class. Pruning is a technique that removes branches from a fully grown tree to improve generalization on unseen data. Cost complexity pruning introduces a regularization parameter that penalizes tree size, creating a relationship between tree complexity and prediction error. Reduced Error Pruning removes nodes if the error on a validation set does not increase or decreases after removal. Setting a maximum tree depth, minimum samples per leaf, and minimum samples for splitting are hyperparameters that control tree growth and can prevent overfitting. Cross-validation helps select optimal values for these hyperparameters by evaluating performance on held-out data.",
        "### Feature Interactions and Interpretability\n\nOne of the major advantages of decision trees is their interpretability; the decision rules can be easily extracted and visualized as a tree structure. This makes decision trees valuable in applications where model transparency is important, such as healthcare or finance. Decision trees naturally capture feature interactions without requiring explicit feature engineering, as the model learns hierarchical combinations of conditions. A complex interaction that might require manual feature engineering in linear models emerges naturally through the tree structure. However, this interpretability comes with a cost: decision trees tend to create boundaries parallel to feature axes and can be unstable, where small changes in training data lead to significantly different tree structures.",
        "### Handling Missing Values and Categorical Features\n\nDecision trees handle both categorical and continuous features naturally without requiring extensive preprocessing. For categorical features, binary splits can group categories or make simple left-right decisions. For continuous features, the optimal split point is found by sorting unique feature values and evaluating each potential threshold. Missing values can be handled through surrogate splits, which identify alternative features that produce similar splits when the primary feature is missing. Some implementations use weighted samples to handle missing data, distributing samples that contain missing values down both left and right branches proportionally. This flexibility makes decision trees particularly useful in real-world scenarios where data completeness cannot be guaranteed."
    ],
    "04-random_forest": [
        "### Bootstrap Aggregating and Ensemble Power\n\nRandom Forests leverage the principle of bootstrap aggregating (bagging) to create multiple diverse decision trees and combine their predictions through averaging or voting. Each tree is grown on a bootstrap sample—a random sample with replacement from the original training set. This sampling strategy ensures that each tree trains on slightly different data, creating diversity in the ensemble. The diversity is crucial because when combining predictions from correlated models, the ensemble performs similar to a single model; diversity allows uncorrelated errors to cancel out, significantly reducing variance. By averaging predictions from many trees (for regression) or taking majority votes (for classification), Random Forests achieve substantially lower variance than individual decision trees while maintaining comparable bias.",
        "### Random Feature Selection at Each Split\n\nWhile bagging creates data diversity through bootstrap sampling, Random Forests introduce additional diversity by randomly selecting features at each split. At each node, instead of searching through all features for the best split, only a random subset of features is considered. Typically, m features are randomly selected from the total p available features, where m ≈ √p for classification and m ≈ p/3 for regression. This randomization serves multiple purposes: it reduces correlation between trees by preventing dominant features from appearing at every split, it decreases computational cost by evaluating fewer features, and it encourages the model to find alternative features that provide similar predictive power. This two-level randomization—from bootstrap samples and random feature selection—is what distinguishes Random Forests from standard bagging with decision trees.",
        "### Out-of-Bag Error and Feature Importance\n\nSince each bootstrap sample typically includes approximately 63% of the original data, the remaining 37% (out-of-bag samples) can be used for validation without requiring a separate test set. Out-of-bag error provides an unbiased estimate of generalization performance and can be used to monitor overfitting during training. Additionally, Random Forests can compute feature importance by measuring the decrease in impurity (for classification) or variance (for regression) across all splits using a particular feature. Features that frequently provide large decreases in impurity are considered more important. Mean Decrease in Accuracy and Mean Decrease in Gini are two common importance measures. This feature importance information is valuable for feature engineering, identifying irrelevant features, and gaining insights into which variables drive predictions.",
        "### Parallel Training and Scalability\n\nA significant practical advantage of Random Forests is that each tree can be trained independently, making the algorithm embarrassingly parallel. In practice, trees can be grown simultaneously on different processors or machines, making Random Forests highly scalable to large datasets. The training time scales roughly linearly with the number of trees, and with parallelization, the wall-clock time can be significantly reduced. However, prediction time still requires aggregating predictions from all trees, which takes time linear in the number of trees. For very large datasets, practitioners might use a smaller number of trees or employ distributed computing frameworks like Apache Spark. Random Forests have proven effective in numerous applications from bioinformatics to finance, often serving as a strong baseline model that benefits from minimal hyperparameter tuning compared to other algorithms."
    ],
    "05-support_vector_machines": [
        "### The Maximum Margin Principle\n\nSupport Vector Machines (SVMs) are based on the principle of finding the optimal separating hyperplane that maximizes the margin between classes. The margin is defined as the distance from the hyperplane to the nearest data points of either class. SVMs solve the optimization problem of finding the hyperplane W that maximizes this margin while correctly classifying all training examples. Mathematically, this is formulated as minimizing ||W||² subject to the constraint that y_i(W·x_i + b) ≥ 1 for all training examples. The maximum margin principle provides strong generalization guarantees; a larger margin means the hyperplane is more robust to small perturbations in the data. The data points closest to the hyperplane that define the margin are called support vectors, and only these points are needed to define the decision boundary, making SVMs memory-efficient for prediction.",
        "### Handling Non-Linear Separability with Kernels\n\nMost real-world classification problems are not linearly separable in the input space. SVMs handle this through the kernel trick, which implicitly projects data into a higher-dimensional feature space where linear separation becomes possible. Common kernels include the polynomial kernel K(x, x') = (x·x' + c)^d, the radial basis function (RBF) kernel K(x, x') = exp(-γ||x - x'||²), and the sigmoid kernel. The key insight of the kernel trick is that the computation can be done in the original input space using kernel functions without explicitly computing the high-dimensional projection. The RBF kernel is particularly popular because it can handle complex non-linear patterns effectively without over-parameterization. The kernel parameter γ controls the reach of each training example; small γ leads to smooth boundaries while large γ creates more intricate patterns following individual data points.",
        "### Soft Margin Formulation and Regularization\n\nStrict maximum margin formulation assumes perfect linear (or kernel-induced) separability, which is unrealistic when classes overlap or noise is present. The soft margin formulation introduces slack variables ξ_i that allow some misclassification, leading to the optimization problem: minimize ||W||² + C·Σξ_i subject to y_i(W·x_i + b) ≥ 1 - ξ_i. The regularization parameter C controls the trade-off between maximizing the margin and minimizing classification error. Large C values penalize misclassifications heavily, leading to complex decision boundaries that fit training data closely, while small C values allow more training errors for a larger margin and simpler decision boundaries. Cross-validation is used to select an appropriate C value. The soft margin formulation also applies when using kernels, making SVMs practical for real-world noisy datasets.",
        "### Multi-class Classification and Practical Considerations\n\nSVMs are primarily designed for binary classification, but several strategies extend them to multi-class problems. One-vs-Rest creates |K| binary classifiers, each trained to separate one class from all others. One-vs-One creates |K|(|K|-1)/2 binary classifiers for each pair of classes. The predictions from multiple binary classifiers are combined through voting or probability calibration. In practice, implementing SVMs involves several considerations: feature scaling is critical since SVMs are sensitive to the magnitude of features, kernel selection requires domain knowledge or cross-validation, and training time complexity is O(n²) or O(n³) depending on the implementation, making SVMs less suitable for very large datasets. However, SVMs provide strong theoretical guarantees on generalization and remain competitive for medium-sized datasets, particularly in high-dimensional spaces where the margin principle provides substantial benefits."
    ],
    "06-naive_bayes": [
        "### Bayes' Theorem and Probabilistic Classification\n\nNaive Bayes classifiers are based on Bayes' theorem, which describes how to update probabilities based on evidence. Bayes' theorem states: P(y|x) = P(x|y)·P(y) / P(x), where P(y|x) is the posterior probability of class y given features x, P(x|y) is the likelihood, P(y) is the prior probability, and P(x) is the evidence. For classification, we want to find the class y that maximizes P(y|x). Since P(x) is constant across classes, we need to maximize P(x|y)·P(y). The prior P(y) is estimated from the proportion of training examples in each class. The likelihood P(x|y) requires computing the joint probability of all features given a class, which becomes problematic in high dimensions due to sparse data. This is where the naive assumption becomes crucial.",
        "### The Naive Conditional Independence Assumption\n\nThe naive assumption is that features are conditionally independent given the class label, meaning P(x₁, x₂, ..., xₚ|y) = ∏P(xᵢ|y). This assumption is rarely true in practice—features are often correlated—but it drastically simplifies the model and computation. Instead of estimating a complex high-dimensional distribution, we only need to estimate p univariate distributions. For each feature and class combination, we estimate P(xᵢ|y) from training data. For discrete features, this is simply the proportion of class y examples where feature i takes value xᵢ. For continuous features, we typically assume a Gaussian distribution and estimate the mean and variance for each feature-class combination. The strong independence assumption, while often violated, frequently leads to effective classifiers because it reduces variance through model simplification, sometimes outperforming more complex models despite the unrealistic assumptions.",
        "### Gaussian, Multinomial, and Bernoulli Variants\n\nThe choice of how to model feature distributions leads to different Naive Bayes variants. Gaussian Naive Bayes assumes continuous features follow a normal distribution, computing P(xᵢ|y) = (1/√(2π·σ²ᵧᵢ))·exp(-(xᵢ-μᵧᵢ)²/(2σ²ᵧᵢ)). Multinomial Naive Bayes is designed for discrete count data and is commonly used in text classification, where features represent word frequencies or term frequencies. Bernoulli Naive Bayes is used when features are binary (present or absent), appropriate for document classification with binary feature vectors indicating word presence. Each variant models feature distributions appropriately for the data type, yet all follow the same classification principle of selecting the class with maximum posterior probability. Understanding which variant matches your data type and problem domain is crucial for effective implementation.",
        "### Advantages, Limitations, and Practical Applications\n\nNaive Bayes offers several practical advantages: it is computationally efficient, training is linear in the number of features and training examples, and it requires relatively small amounts of training data compared to more complex models. The algorithm produces calibrated probability estimates and naturally handles missing data by ignoring missing features during inference. However, Naive Bayes struggles with correlated features due to the independence assumption and may underperform complex models on problems with intricate feature interactions. The assumption that class priors remain constant can be problematic with imbalanced datasets. Despite its simplicity, Naive Bayes remains highly effective for text classification, spam detection, and sentiment analysis. Many practitioners use it as a baseline model; if more sophisticated algorithms achieve only marginally better performance, the simplicity and interpretability of Naive Bayes make it the preferred choice."
    ],
    "07-k_nearest_neighbors": [
        "### Instance-Based Learning and the k-NN Algorithm\n\nK-Nearest Neighbors (k-NN) is a non-parametric, instance-based learning algorithm that makes predictions based on the k most similar examples in the training set. Unlike algorithms that learn explicit models during training, k-NN stores all training examples and makes decisions at prediction time. For a query point, the algorithm finds the k nearest training examples using a distance metric (typically Euclidean distance), and for classification, assigns the class that appears most frequently among the k neighbors. For regression, it averages the target values of the k neighbors. The simplicity of k-NN makes it easy to understand and implement, but this simplicity comes with significant computational costs: prediction time is linear in the training set size, and storing all training data consumes substantial memory for large datasets.",
        "### Distance Metrics and Feature Scaling\n\nThe choice of distance metric significantly impacts k-NN performance. Euclidean distance is most common but assumes all features contribute equally to similarity. Manhattan distance (absolute value differences) can be more robust to outliers in some applications. Minkowski distance provides a family of metrics parametrized by p: d(x, y) = (Σ|xᵢ - yᵢ|^p)^(1/p). Mahalanobis distance accounts for feature correlations and differing scales. Feature scaling becomes critical because k-NN uses distances directly without learning feature weights; features with larger numerical ranges dominate distance calculations. Standardization (z-score normalization) ensures each feature contributes proportionally to distances. Additionally, irrelevant features increase noise and computational cost; feature selection or dimensionality reduction is often necessary before applying k-NN, especially in high-dimensional spaces where the curse of dimensionality causes distance-based similarity to become less meaningful.",
        "### Choosing k and Bias-Variance Tradeoff\n\nThe hyperparameter k controls the neighborhood size and creates a fundamental bias-variance tradeoff. Small k values (e.g., k=1) create complex decision boundaries that closely follow training data, resulting in low bias but high variance and susceptibility to noise and outliers. Large k values use broader neighborhoods, creating smoother decision boundaries with higher bias but lower variance. The optimal k depends on data complexity and noise level; noisier data benefits from larger k values. Cross-validation helps select k by evaluating performance on held-out data across different k values. In practice, k=5 or k=10 often serve as reasonable defaults, though domain knowledge and characteristics of the specific dataset should guide the choice. Odd values of k are preferred for binary classification to avoid ties, though sophisticated tiebreaking strategies can handle this.",
        "### Computational Efficiency and Practical Improvements\n\nThe O(n) prediction time cost of k-NN is prohibitive for large datasets. Various techniques address this limitation: KD-trees and ball trees index data hierarchically, allowing nearest neighbor searches in O(log n) time on average. Locality-Sensitive Hashing (LSH) enables fast approximate nearest neighbor search. These data structures become particularly important in high dimensions where brute-force search is the only viable option. Approximate k-NN methods return nearby neighbors rather than exact nearest neighbors, providing substantial speedups with minimal accuracy loss. Additionally, k-NN performs well on small to medium-sized datasets with low to moderate dimensionality. For text data or high-dimensional spaces, cosine similarity is more appropriate than Euclidean distance. Despite its limitations, k-NN remains valuable for non-linear problems, local pattern detection, and as a baseline model; its interpretability also makes it useful in exploratory data analysis."
    ],
    "08-gradient_boosting": [
        "### Boosting Ensemble Strategy and Sequential Models\n\nGradient Boosting builds an ensemble of weak learners sequentially, where each new learner focuses on correcting the mistakes made by previous learners. Unlike bagging, which trains models in parallel on random subsets, boosting is inherently sequential: each iteration fits a new model to the residuals (negative gradients) of previous predictions. This sequential nature creates strong dependencies between models but dramatically reduces bias. The final prediction is a weighted sum of all weak learner predictions. The boosting principle is powerful: weak learners, individual models that perform only slightly better than random guessing, can be combined into a strong ensemble that achieves excellent performance. This is formalized in boosting theory, which provides bounds on generalization error in terms of training error and the diversity of weak learners.",
        "### Gradient Descent in Function Space\n\nGradient Boosting generalizes the boosting framework using gradient descent in function space. Each iteration computes the negative gradient of a loss function with respect to current predictions, identifying the direction that would most reduce loss. A new weak learner (typically shallow decision trees called stumps) is fit to predict these negative gradients. The predictions from this learner are scaled by a learning rate η and added to the ensemble: F_{m+1}(x) = F_m(x) + η·h_m(x), where h_m predicts gradients. The learning rate controls how much each weak learner adjusts the ensemble, providing regularization through slower learning. Smaller learning rates require more iterations but often produce better generalization. The loss function—squared error, absolute error, log loss, or custom functions—can be chosen based on the problem  and determines the gradient direction at each iteration.",
        "### Subsampling and Regularization Strategies\n\nGradient Boosting is prone to overfitting, especially with high learning rates or many iterations. Several regularization strategies mitigate this risk. Stochastic Gradient Boosting randomly subsamples training data at each iteration (row sampling) and randomly selects features (column sampling) when fitting weak learners. This introduces variance that can offset overfitting while maintaining efficiency. Early stopping monitors validation loss and terminates training when performance plateaus, preventing training on too many iterations. Shrinkage limits the contribution of each weak learner through the learning rate η; smaller values require more iterations but improve generalization. Tree depth constraints limit weak learner complexity, typically using depth 3-8 for stumps. Regularization parameters can be tuned through cross-validation or grid search. The combination of multiple regularization strategies—subsampling, early stopping, shrinkage, and weak learner constraints—is typically necessary to achieve good generalization with Gradient Boosting.",
        "### Practical Implementation and Hyperparameter Tuning\n\nSuccessful Gradient Boosting requires careful hyperparameter tuning. Key hyperparameters include the number of iterations (trees), learning rate, tree depth, minimum samples per leaf, and subsampling rates. The learning rate and number of iterations are coupled; lower learning rates benefit from more iterations. A common strategy is to fix the learning rate at a reasonable value (e.g., 0.01-0.1) and use early stopping to determine the number of iterations. Tree depth is often set to 3-8; deeper trees increase model complexity and risk overfitting. Modern implementations like XGBoost, LightGBM, and CatBoost provide additional optimizations and regularization options. XGBoost adds an L1/L2 regularization term to the loss function. LightGBM uses leaf-wise tree growth instead of level-wise, improving efficiency. CatBoost handles categorical features automatically without manual encoding. These implementations have made Gradient Boosting one of the most effective and popular algorithms in practice, winning numerous machine learning competitions."
    ]
}

def add_content_with_commits(module_dir, subdir, content_list):
    """Add content to README.md and make commits for each paragraph."""
    readme_path = Path(module_dir) / subdir / "README.md"
    
    if not readme_path.exists():
        print(f"README not found: {readme_path}")
        return False
    
    # Read existing content
    with open(readme_path, 'r', encoding='utf-8') as f:
        original_content = f.read()
    
    # Add each paragraph with a commit
    for i, paragraph in enumerate(content_list, 1):
        # Add content to file
        with open(readme_path, 'a', encoding='utf-8') as f:
            f.write("\n\n" + paragraph)
        
        # Stage and commit
        subprocess.run(['git', 'add', str(readme_path)], cwd=str(Path(module_dir).parent.parent.parent))
        commit_msg = f"Add {subdir.replace('_', ' ').title()} content - Section {i}/4"
        subprocess.run(['git', 'commit', '-m', commit_msg], cwd=str(Path(module_dir).parent.parent.parent))
        print(f"✓ Committed: {subdir} - Paragraph {i}/4")
    
    return True

# Main execution
module_1_1 = Path("modules/module-1.1")
subcategories = [
    ("1_supervised_learning", list(content_map.keys())),
    ("2_unsupervised_learning", ["01-k_means", "02-hierarchical_clustering", "03-pca", "04-dbscan", "05-gmm", "06-manifold_learning"]),
    ("3_reinforcement_learning", ["01-q_learning", "02-policy_gradient", "03-actor_critic", "04-deep_q_networks"])
]

total_commits = 0

# Process supervised learning
for subdir, algorithms in [("1_supervised_learning", list(content_map.keys()))]:
    for algo in algorithms:
        if algo in content_map:
            print(f"\nProcessing {algo}...")
            algo_dir = module_1_1 / subdir / f"{algo.replace('_', '-')}"
            if add_content_with_commits(module_1_1, f"{subdir}/{algo}", content_map[algo]):
                total_commits += 4
                print(f"  → Total commits so far: {total_commits}")

print(f"\n✅ Added {total_commits} commits for supervised learning content")
print("Please continue with unsupervised and reinforcement learning sections...")
